########################################################################################################################
# Invoked by tmux automatically when starting. Save as `$HOME/.tmux.conf`.
########################################################################################################################

set -g default-terminal "screen-256color"       # Default 256 colour terminal.
set -g allow-rename off                         # Don't auto rename windows.
set -g base-index 1                             # Start window index at 1.
set -g pane-base-index 1                        # Start pane index at 1.
set -g status-interval 3                        # Status bar refresh rate.
set -g prefix C-a                               # Set prefix key to Ctrl+a.
setw -g mode-keys vi                            # Use VI key bindings in copy mode.

# Status bar styles.
set -g status-right 'CPU: #{cpu_percentage} | %H:%M | %a %d/%m/%Y '

# Key bindings.
bind C-a send-prefix                            # Prefix: C-a
bind + new-window                               # New window: +
bind X kill-window                              # Kill window: X
bind x kill-pane                                # Kill pane: x
unbind C-b
unbind c
unbind &

# plugin settings.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-cpu'
run -b '~/.tmux/plugins/tpm/tpm'
